name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: {Container_Registry_Name}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${Container_Registry_Name}/${{ github.repository }}/orchestrator
          COMMIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:$COMMIT_SHA .

      - name: Push Docker image
        run: |
          IMAGE_NAME=${Container_Registry_Name}/${{ github.repository }}/orchestrator
          COMMIT_SHA=${{ github.sha }}
          docker push $IMAGE_NAME:$COMMIT_SHA

